// AI-CONTEXT: Barrel export for all entity metadata hooks in the metadata-samples project.
// AI-CONSTRAINT: Export both the hook function and its result interface for each entity.
// AI-PATTERN: One export block per hook, alphabetical by entity name.

export type { IEntityTableInfo } from './entityMetadata.types'

export { useAadUserMetadata } from './useAadUserMetadata'
export type { IUseAadUserMetadataResult } from './useAadUserMetadata'
export { useAccountMetadata } from './useAccountMetadata'
export type { IUseAccountMetadataResult } from './useAccountMetadata'
export { useAppEventLogMetadata } from './useAppEventLogMetadata'
export type { IUseAppEventLogMetadataResult } from './useAppEventLogMetadata'
export { useAppointmentMetadata } from './useAppointmentMetadata'
export type { IUseAppointmentMetadataResult } from './useAppointmentMetadata'
export { useAuditMetadata } from './useAuditMetadata'
export type { IUseAuditMetadataResult } from './useAuditMetadata'
export { useBusinessUnitMetadata } from './useBusinessUnitMetadata'
export type { IUseBusinessUnitMetadataResult } from './useBusinessUnitMetadata'
export { useConfigurationSettingMetadata } from './useConfigurationSettingMetadata'
export type { IUseConfigurationSettingMetadataResult } from './useConfigurationSettingMetadata'
export { useContactMetadata } from './useContactMetadata'
export type { IUseContactMetadataResult } from './useContactMetadata'
export { useCustomApiMetadata } from './useCustomApiMetadata'
export type { IUseCustomApiMetadataResult } from './useCustomApiMetadata'
export { useCustomApiRequestParameterMetadata } from './useCustomApiRequestParameterMetadata'
export type { IUseCustomApiRequestParameterMetadataResult } from './useCustomApiRequestParameterMetadata'
export { useCustomApiResponsePropertyMetadata } from './useCustomApiResponsePropertyMetadata'
export type { IUseCustomApiResponsePropertyMetadataResult } from './useCustomApiResponsePropertyMetadata'
export { useEmailMetadata } from './useEmailMetadata'
export type { IUseEmailMetadataResult } from './useEmailMetadata'
export { useEntitiesMetadata } from './useEntitiesMetadata'
export type { IUseEntitiesMetadataResult } from './useEntitiesMetadata'
export { useEnvironmentVariableDefinitionMetadata } from './useEnvironmentVariableDefinitionMetadata'
export type { IUseEnvironmentVariableDefinitionMetadataResult } from './useEnvironmentVariableDefinitionMetadata'
export { useEnvironmentVariableValueMetadata } from './useEnvironmentVariableValueMetadata'
export type { IUseEnvironmentVariableValueMetadataResult } from './useEnvironmentVariableValueMetadata'
export { useLeadMetadata } from './useLeadMetadata'
export type { IUseLeadMetadataResult } from './useLeadMetadata'
export { useOpportunityMetadata } from './useOpportunityMetadata'
export type { IUseOpportunityMetadataResult } from './useOpportunityMetadata'
export { useSavedQueriesMetadata } from './useSavedQueriesMetadata'
export type { IUseSavedQueriesMetadataResult } from './useSavedQueriesMetadata'
export { useSolutionComponentDefinitionMetadata } from './useSolutionComponentDefinitionMetadata'
export type { IUseSolutionComponentDefinitionMetadataResult } from './useSolutionComponentDefinitionMetadata'
export { useSolutionComponentMetadata } from './useSolutionComponentMetadata'
export type { IUseSolutionComponentMetadataResult } from './useSolutionComponentMetadata'
export { useSolutionMetadata } from './useSolutionMetadata'
export type { IUseSolutionMetadataResult } from './useSolutionMetadata'
export { useSystemFormMetadata } from './useSystemFormMetadata'
export type { IUseSystemFormMetadataResult } from './useSystemFormMetadata'
export { useSystemUserMetadata } from './useSystemUserMetadata'
export type { IUseSystemUserMetadataResult } from './useSystemUserMetadata'
export { useTaskMetadata } from './useTaskMetadata'
export type { IUseTaskMetadataResult } from './useTaskMetadata'
export { useTeamMetadata } from './useTeamMetadata'
export type { IUseTeamMetadataResult } from './useTeamMetadata'
export { useTransactionCurrencyMetadata } from './useTransactionCurrencyMetadata'
export type { IUseTransactionCurrencyMetadataResult } from './useTransactionCurrencyMetadata'
export { useWebresourceMetadata } from './useWebresourceMetadata'
export type { IUseWebresourceMetadataResult } from './useWebresourceMetadata'
export { useSubscriptionMetadata } from './useSubscriptionMetadata'
export type { IUseSubscriptionMetadataResult } from './useSubscriptionMetadata'
