// AI-CONTEXT: Loads Dataverse SolutionComponent records, optionally scoped to a specific solution and/or component type.
// AI-FILE-RELATIONS:
//   - service: src/generated/services/SolutioncomponentsService.ts  (PAC-generated CRUD layer — used by both hooks)
//   - service: src/generated/services/SolutionsService.ts            (PAC-generated CRUD layer — used by useSolutionComponentsByType step 2)
//   - model:   src/generated/models/SolutioncomponentsModel.ts       (Solutioncomponents entity interface and enums)
// AI-CONSTRAINT: Never edit files under src/generated/ — they are regenerated by pac CLI tooling.
// AI-PATTERN: All setState calls live inside .then()/.catch()/.finally() async callbacks — never synchronously in the effect body (react-hooks v7 rule).
// AI-PATTERN: useSolutionComponentsByType uses a two-step fetch (SolutioncomponentsService → SolutionsService) because IGetAllOptions does not support $expand and raw fetch is blocked by CSP.

import { useState, useEffect, useCallback } from 'react'
import { SolutioncomponentsService } from '../../generated/services/SolutioncomponentsService'
import { SolutionsService } from '../../generated/services/SolutionsService'
import type { Solutioncomponents, Solutioncomponentscomponenttype } from '../../generated/models/SolutioncomponentsModel'

/** Result returned by {@link useSolutionComponents}. */
export interface IUseSolutionComponentsResult {
  /** Solution component records matching the current filter parameters. */
  solutionComponents: Solutioncomponents[]
  /** Whether data is currently loading. */
  loading: boolean
  /** Error from the last failed fetch, or `null`. */
  error: Error | null
  /** Re-fetches solution components and resets the loading indicator. */
  reload: () => void
}

/**
 * Loads Dataverse `solutioncomponents` records, ordered by component type.
 *
 * @remarks
 * Dataverse table: `solutioncomponents`
 * OData filter: `_solutionid_value eq '<solutionId>'` (when provided), and
 * `componenttype eq <componenttype>` (when provided).
 * Both parameters are optional — omitting both returns all solution components
 * across all solutions.
 *
 * On filter-param changes the previous data remains visible (stale-while-revalidate)
 * until the new fetch completes. Call `reload()` to explicitly show the loading
 * indicator and re-fetch with the current parameters.
 *
 * @param solutionId - Optional GUID of the solution to scope the query to
 *   (matches `_solutionid_value`).
 * @param componenttype - Optional component-type numeric key to further narrow
 *   results (e.g. `61` for WebResource, `60` for SystemForm).
 * @returns Solution component records, loading state, error state, and a `reload` callback.
 *
 * @example
 * ```ts
 * // All components in a specific solution
 * const { solutionComponents, loading } = useSolutionComponents('a1b2c3d4-...')
 *
 * // Only web resources in a specific solution
 * const { solutionComponents } = useSolutionComponents('a1b2c3d4-...', 61)
 * ```
 */
export function useSolutionComponents(
  solutionId?: string,
  componenttype?: Solutioncomponentscomponenttype,
): IUseSolutionComponentsResult {
  const [solutionComponents, setSolutionComponents] = useState<Solutioncomponents[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<Error | null>(null)
  // AI-CONTEXT: Incrementing this counter from reload() triggers the effect to re-run without calling setState synchronously inside the effect.
  const [reloadTrigger, setReloadTrigger] = useState(0)

  useEffect(() => {
    let cancelled = false

    // AI-CONTEXT: Build filter clauses independently and join — both params are optional.
    const clauses: string[] = []
    if (solutionId) clauses.push(`_solutionid_value eq '${solutionId}'`)
    if (componenttype !== undefined) clauses.push(`componenttype eq ${componenttype}`)
    const filter = clauses.length > 0 ? clauses.join(' and ') : undefined

    // AI-INTENT: All setState calls are inside async .then()/.catch()/.finally() — never synchronously in the effect body.
    SolutioncomponentsService.getAll({ filter, orderBy: ['componenttype asc'] })
      .then(result => {
        if (cancelled) return
        if (!result.success) throw new Error('Failed to load solution components')
        setSolutionComponents(result.data ?? [])
        setError(null)
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setError(err instanceof Error ? err : new Error(String(err)))
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => { cancelled = true }
  }, [solutionId, componenttype, reloadTrigger])

  // AI-INTENT: setLoading(true) here is called from a user-event callback, not from an effect — the react-hooks rule does not apply.
  const reload = useCallback(() => {
    setLoading(true)
    setReloadTrigger(c => c + 1)
  }, [])

  return { solutionComponents, loading, error, reload }
}

/**
 * A Dataverse solution that contains a specific component.
 *
 * @remarks
 * Populated via `SolutionsService.getAll` with
 * `$select=uniquename,friendlyname,version,ismanaged,solutionid`.
 */
export interface ISolutionInfo {
  /** Unique name of the solution (e.g. `'Active'`, `'mySolution'`). */
  uniqueName: string
  /** Display name shown in the Power Apps maker portal. */
  friendlyName: string
  /** Solution version string (e.g. `'1.0.0.0'`). */
  version: string
  /** Whether the solution is managed (read-only in the target environment). */
  isManaged: boolean
  /** GUID of the solution record in Dataverse. */
  solutionId: string
}

/** Result returned by {@link useSolutionComponentsByType}. */
export interface IUseSolutionComponentsByTypeResult {
  /** Solutions that contain the specified component, derived from the expanded `solutionid` navigation property. */
  solutions: ISolutionInfo[]
  /** Whether data is currently loading. */
  loading: boolean
  /** Error from the last failed fetch, or `null`. */
  error: Error | null
  /** Re-fetches and resets the loading indicator. */
  reload: () => void
}

/**
 * Returns the solutions that contain a specific component, identified by component type and object ID.
 *
 * @remarks
 * Uses a two-step PAC SDK fetch to avoid CSP restrictions on raw `fetch` and the lack of
 * `$expand` support in `IGetAllOptions`:
 *
 * **Step 1** — `SolutioncomponentsService.getAll` with
 * `$filter=componenttype eq <N> and objectid eq <GUID>&$select=_solutionid_value`
 * to retrieve the solution GUIDs that own this component.
 *
 * **Step 2** — `SolutionsService.getAll` with
 * `$filter=solutionid eq X or solutionid eq Y&$select=uniquename,friendlyname,version`
 * to retrieve the full solution details.
 *
 * Returns an empty array (not an error) when the component belongs to no solutions.
 *
 * @param componenttype - Numeric component-type key from `Solutioncomponentscomponenttype`
 *   (e.g. `1` for Entity, `61` for WebResource, `60` for SystemForm).
 * @param objectid - GUID of the component object to look up (e.g. the `MetadataId` of an entity).
 * @returns The list of solutions containing the component, loading state, error state, and a `reload` callback.
 *
 * @example
 * ```ts
 * // Find all solutions that contain the Account entity (componenttype 1)
 * const { solutions, loading } = useSolutionComponentsByType(1, accountMetadataId)
 * ```
 */
export function useSolutionComponentsByType(
  componenttype: Solutioncomponentscomponenttype,
  objectid: string,
): IUseSolutionComponentsByTypeResult {
  const [solutions, setSolutions] = useState<ISolutionInfo[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<Error | null>(null)
  // AI-CONTEXT: Incrementing this counter from reload() triggers the effect to re-run without calling setState synchronously inside the effect.
  const [reloadTrigger, setReloadTrigger] = useState(0)

  useEffect(() => {
    let cancelled = false
    // AI-CONTEXT: Skip when objectid is empty — MetadataId (or equivalent) may not be resolved yet on first render.
    // AI-INTENT: setLoading is called inside .then() rather than synchronously to satisfy the react-hooks v7 rule.
    if (!objectid) {
      Promise.resolve().then(() => { if (!cancelled) setLoading(false) })
      return () => { cancelled = true }
    }

    // AI-CONTEXT: Step 1 — get solutioncomponent records to extract _solutionid_value GUIDs.
    // AI-CONTEXT: objectid is an Edm.Guid — passed without quotes in OData v4 filter syntax.
    // AI-INTENT: All setState calls are inside async .then()/.catch()/.finally() — never synchronously in the effect body.
    SolutioncomponentsService.getAll({
      filter: `componenttype eq ${componenttype} and objectid eq ${objectid}`,
      select: ['_solutionid_value'],
    })
      .then(result => {
        if (cancelled) return null
        if (!result.success) throw new Error('Failed to load solution components')
        // AI-CONTEXT: Deduplicate solution IDs — a component may appear more than once per solution (subcomponents).
        const solutionIds = [...new Set(
          (result.data ?? []).map(c => c._solutionid_value).filter((id): id is string => Boolean(id))
        )]
        if (solutionIds.length === 0) return null
        // AI-CONTEXT: Step 2 — fetch solution details for all resolved solution IDs in one call.
        // AI-INTENT: isvisible eq true excludes internal/hidden solutions (e.g. 'Active', 'Basic Solution') from the results.
        return SolutionsService.getAll({
          filter: `(${solutionIds.map(id => `solutionid eq ${id}`).join(' or ')}) and isvisible eq true`,
          select: ['uniquename', 'friendlyname', 'version', 'ismanaged', 'solutionid'],
        })
      })
      .then(result => {
        if (cancelled) return
        // AI-CONTEXT: null result means the component belongs to no solutions — set empty array, not an error.
        if (!result) { setSolutions([]); setError(null); return }
        if (!result.success) throw new Error('Failed to load solutions')
        setSolutions((result.data ?? []).map(s => ({
          uniqueName: s.uniquename ?? '',
          friendlyName: s.friendlyname ?? '',
          version: s.version ?? '',
          isManaged: s.ismanaged ?? false,
          solutionId: s.solutionid ?? '',
        })))
        setError(null)
      })
      .catch((err: unknown) => {
        if (cancelled) return
        setError(err instanceof Error ? err : new Error(String(err)))
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => { cancelled = true }
  }, [componenttype, objectid, reloadTrigger])

  // AI-INTENT: setLoading(true) here is called from a user-event callback, not from an effect — the react-hooks rule does not apply.
  const reload = useCallback(() => {
    setLoading(true)
    setReloadTrigger(c => c + 1)
  }, [])

  return { solutions, loading, error, reload }
}
