version: 2
updates:
  - package-ecosystem: npm
    directory: /src/basic-sample
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - basic-sample

  - package-ecosystem: npm
    directory: /src/dataverse-actions-functions-power-automate-flows-samples
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - dataverse-sample

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
